### ISSUE TITLE
闲着无聊~

### ISSUE THREAD

**Issue by wuww5511** [Becavalier/SwiftSlide#1]
有一种想把你的代码review一遍的冲动~

**Comment by Becavalier** [comment]
Welcome review and issue/optimization suggestions submit !!

**Comment by wuww5511** [comment]
类似`SwiftSlide.isNumeric = function () {}` , `var a = ""` , `SwiftSlide.prototype.shiftOrder = function () {}`这样的东西最好放到`function SwiftSlide () {}`外面。放到 函数里面的东西每次new一个对象的时候都会执行一次，把以前的东西覆盖掉。影响性能是一方面，重要是容易出bug~

`SwiftSlide.prototype.addEventToQueue = function(event) {
            this.eventQueue.push(event);
        };`
执行这个函数的时候会报错吧~ this.eventQueue没有初始化啊~（`var eventQueque = []` 是局部变量，不是成员变量~）

**Comment by Becavalier** [comment]
Yes, initialize object with much of settings is not a very proper plan, I will change this logic and use only one object in the global environment in the next release, for `var eventQueque = []`, it is really a bug, alse will be fixed in the next version.
